name: C++ Build and run

on:
  push:
    paths:
        - 'tag-file.txt'
        - '*.cpp'
        - '.github/workflows/cpp_build_and_run.yml'
  pull_request:
    paths:
      - 'tag-file.txt'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: echo g++ --version
    - name: Build
      run: g++ -o output your_file.cpp
    - name: Run
      run: ./output
